### ISSUE TITLE
Eu encontrei um pequeno bug

### ISSUE THREAD

**Issue by alexandreramosdev** [willianjusten/greensock-course#1]
É este comportamento mesmo?

![screenshot_2018-08-04_21-47-36](https://user-images.githubusercontent.com/34720135/43681639-13158e82-9830-11e8-8f15-dd520e1c4b7b.png)

**Comment by willianjusten** [comment]
Opa @AlexandreRStos , é sim, para explicar que o comando `.set()` define a posição do elemento onde você desejar. 

Você tem o curso? Fazendo o curso dá para entender a razão disso xD

**Comment by alexandreramosdev** [comment]
Blz Willian! 

Foi que vi o site e como sempre te sigo... ai me aparece as suas novidades!!!

Eu não estou fazendo o curso !  
Eu estou começando agora na area de dev web. E estou super sem grana !!!  Ta muito difícil de entrar no mercado !   Mas no futuro estarei fazendo seus cursos!!   

Obs: os free que vc disponibilizou eu já fiz todos! kkk
